/*
Install List:
  @tanstack/react-router 
  @tanstack/router-vite-plugin
*/

import { RouterProvider, createRouter } from '@tanstack/react-router';
import { routeTree } from './routeTree.gen.ts'; // auto-generated by tanstack
import './App.css'

import React from "react";

// Creating a router instance
const router = createRouter({ routeTree });


function App() {
    return <RouterProvider router={router} />;
}

export default App;